CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_BEHAVIOR_CAPS_WORD=y

# PMW3610 sensor tuning
CONFIG_PMW3610_REPORT_INTERVAL_MIN=8

# Input processing
CONFIG_INPUT_QUEUE_MAX_MSGS=32
CONFIG_INPUT_THREAD_STACK_SIZE=768